require: 
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Include:
    - 'app/**/*.rb'
    - 'config/**/*.rb'
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
    - 'spec/**/*.rb'
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/*'

Style/EmptyMethod:
  EnforcedStyle: expanded
Style/Documentation:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/ClassAndModuleChildren:
  Enabled: false
Style/BlockDelimiters:
  BracesRequiredMethods: ['expect']

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'feature']
Bundler/OrderedGems:
  Enabled: false

Capybara/FeatureMethods:
  Enabled: false

RSpec/ExampleLength:
  Max: 10
RSpec/MultipleExpectations:
  Max: 5
RSpec/ImplicitExpect:
  EnforcedStyle: should

Rails/LexicallyScopedActionFilter:
  Enabled: false
Rails/InverseOf:
  Enabled: false
Rails/FilePath:
  Enabled: false